train_args:
  num_epochs: 1
  learning_rate: 8.0e-6
  weight_decay: 0.01
  warmup_steps: 400
  checkpoint: null
  wandb: true
  wandb_project_name: "code-embed"
  wandb_entity: "gpt4all"
  log_grads_every: 100
  log_lr_every: 10
  save_every: 2500
  chunk_size: 1024
  # output_dir: "/work/nvme/bcar/yifeix5/emb_model/control"
  output_dir: "ckpts/qwen7b-coder-instruct-5M-last-token-causal-8e6-eos-token-template"
  # if using deepspeed, this will be ignored
  deepspeed: false
  schedule_type: "linear"
  max_grad_norm: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  grad_cache: false
  loss_fn: "clip"
  use_fp8: false
  clamp_logits: false
  logit_max: 100

model_args:
  model_type: "encoder"
  logit_scale: 50
  trainable_logit_scale: false
  seq_len: 512
  pooling: "last"
  nomic_encoder: true
  use_fused_kernels: false
  add_prefix: true
  num_negatives: 15
  tokenizer_name: "Qwen/Qwen2.5-Coder-7B-Instruct"
  model_name: "Qwen/Qwen2.5-Coder-7B-Instruct"
  pretrained: true
  gradient_checkpointing: true
  # projection_dim: 2048


data_args:
  input_shards: "configs/data/code_finetune_triplets.yaml"
  workers: 0
  batch_size: 128
  seed: 42
  filter_type: "rank"
  filter_k: 2
  filter_256: false
  shuffle: false
  mine_type: "random-weighted"
  neg_start_range: 4
  neg_end_range: 30
  temperature_start: 0.05
  temperature_end: 0.001
  from_hub: true
  download: true
  streaming: false
  weighted_sampling: false
  verbose: false
  text_code: true